### ISSUE TITLE
Are async tests supported?

### ISSUE THREAD

**Issue by DanielMSchmidt** [Hypercubed/chuhai#1]
Hi there,

First of all, thanks for this cool library, I am looking forward to using it! 
My question is if there is an option to allow testing async code. I am using a PubSub library and would like to test a behavior like this:

``` js
var handle = new MyLib();
handle.stream.on('didCall', function(){
  // tell the test case I am done
});

// do stuff, that triggers the stream
```

Is there an option in this library for that? If not, would you like to have one?
Thanks for your time!

**Comment by Hypercubed** [comment]
Have haven't done anything explicitly to support async.  Maybe depends on your test harness and what you are interested in benchmarking.  Take a look here:  https://github.com/Hypercubed/EventsSpeedTests/tree/chuhai?files=1

**Comment by DanielMSchmidt** [comment]
I would love to benchmark the time from invoking a method to the point, where the signal is received. Would a PR, which may add support for async tests make sense to you? I thought of something like

``` js
s.asyncBench('stream', function(promise) {
  var handle = new MyLib();
  handle.stream.on('didCall', function(){
    // tell the test case I am done
    promise.resolve();
  });

   // do stuff, that triggers the str
});
```

**Comment by Hypercubed** [comment]
Looks like benchmarkjs has a differed feature.  I'll look into this.  Maybe as part of the fixtures I'll benchmark setTimeout, next tick, and requestAnimation frame.

PRs are welcome of course.

**Comment by Hypercubed** [comment]
async tests are supported!  They are already built into benchmarkjs.  

Use

```
s.set('defer', true);
```

See here:  https://gist.github.com/Hypercubed/bad6ff5d40ee0252f560f2544ec2310e
use

**Comment by DanielMSchmidt** [comment]
Wow, thanks a lot!
