### ISSUE TITLE
Explain terminology & improve docs?

### ISSUE THREAD

**Issue by kentcdodds** [Hypercubed/chuhai#2]
First, thanks for building this! It looks quite simple!

As I'm trying this out, I have no idea what the output is talking about:

> passing empty array x 3,115,118 ops/sec ±4.20% (10 runs sampled)

It looks good, but what do I do with that knowledge? Can I ensure that the benchmark will fail if it can't run at least 3 mil ops/sec? Also, this API is documented:

> s.set(key: string, value: any)

But there's no documentation on what it's for or what values you'd set. I see in the AVA example that you can set `maxTime` and `minSamples`, but as I change those values in my tests I don't really see what's changing or what it ends up doing.

Mostly I just don't know how to make it so I don't regress on changes. Any tips would be helpful!

**Comment by kentcdodds** [comment]
Here's my PR that explores using this: https://github.com/kentcdodds/match-sorter/pull/6

**Comment by Hypercubed** [comment]
Hi @kentcdodds,

Thank you for the comment.  Yes, I need much better documentation.

As a quick explaination, Chuhai is a wrapper for [bestiejs/benchmark.js](https://github.com/bestiejs/benchmark.js).  The benchmark output is the same as benchmark.js and the `s.set` API is a "proxy" for [Benchmark.options](https://benchmarkjs.com/docs#options).

The reason I created this tool is to be compatible with AVA, and other test systems, to ensure the benchmarks are running correctly.  I've seen many benchmarks (including my own) were a logic error in one or more benchmark renders the result useless.  Additionally to combine benchmark.js with an asynchronous test harness is difficult.  My hope is that Chuhai makes it easier.

As far as regressing on changes, if I understand correctly, you want to ensure that code changes do not significantly change benchmarks vs. previous versions.  I was doing something like this in [mini-signals](https://github.com/Hypercubed/mini-signals/tree/master/bench) by copying versioned source files to test the latest version against.  This was before Chuhai and not a great solution in general.  I'd be happy to discuss how to make this more smooth, either through Chuhai or other tooling.

**Comment by kentcdodds** [comment]
Great, thanks for explaining that to me! What I'd really like is the ability to set a threshold of ops/second or something like that. So the test would fail if ops/second dropped below a given threshold. That would be great. Do you think that'd be possible/useful?

**Comment by Hypercubed** [comment]
I don't have a good idea how to accomplish that at the moment.  The ops/second is device dependent.  Perhaps you need to compare it to a baseline and test if it is below a baseline.  Far from deterministic.

**Comment by kentcdodds** [comment]
Ah, that makes sense. Hmmm... I'm struggling to see how benchmarking can be reliably tracked when it changes so much based on the device it's running on. :-(

**Comment by kentcdodds** [comment]
Beyond that, I'm uncertain of the ability of benchmarking to ensure you avoid regressions as well as to know where hot code paths are and where to optimize.
