### ISSUE TITLE
Maintenance? Burn-in tests?

### ISSUE THREAD

**Issue by OliverUv** [Hypercubed/chuhai#3]
Hello!

I see it's been a while since you updated this project. Benchmark has had a bunch of updates since. Do you intend to keep maintaining it? I'm considering using it at my company, and am wondering if we'll need to take over maintenance (fork if necessary), or if you plan to work on it, or would have time to take pull requests?

Second, I'm wondering what the burn-in thing is? I see that it adds a burn option to benchmark's options, but I can't find anything about burn in the benchmark docs. Is it undocumented, or something old?

**Comment by OliverUv** [comment]
Oh, and a third question: Would you be interested in a conversion of this to TypeScript? (JS users of the library will notice no difference, but TS users will always have up to date type info)

I think the time it would take to bang out the types would be only a small bit lower than the time to port it to TS, and it'd save work in the long run. (Though I haven't implemented this export pattern in TS before, I think it should be possible)

**Comment by Hypercubed** [comment]
I would love to see contributions​.  I think there is a lot of room to improve this project, TS included.  Perso Ally, I haven't have a need to update this project in a while.

**Comment by Hypercubed** [comment]
Burn in is something I added.  It is a benchmark run just like any other, but the results are not ranked and compared in the output.
